### ISSUE TITLE
Setup Issues

### ISSUE THREAD

**Issue by sealneaward** [harvitronix/five-video-classification-methods#1]
Hi.
Didn't want to seem too nit picky, but this may come up as an issue for others as well.

### Setup

In the installation, the unrar command is slightly off

```
Then extract it with unrar -e UCF101.rar.
```

Should be

```
Then extract it with unrar e UCF101.rar.
```

### Missing Files

When running `python 1_move_files.py `

```python
Traceback (most recent call last):
  File "1_move_files.py", line 81, in <module>
    main()
  File "1_move_files.py", line 75, in main
    group_lists = get_train_test_lists()
  File "1_move_files.py", line 20, in get_train_test_lists
    with open(test_file) as fin:
IOError: [Errno 2] No such file or directory: './ucfTrainTestlist/testlist01.txt
```

Thanks for the repo. It looks well laid out. Can't wait to play with the models.

**Comment by harvitronix** [comment]
Thanks, @sealneaward! Fixed.
