### ISSUE TITLE
testlist01.txt

### ISSUE THREAD

**Issue by alaa-Mz** [harvitronix/five-video-classification-methods#127]
why the dataset divided into multiple versions of testlist01.txt and trainlist01.txt?
and if I have different dataset how I can make these txt files automatically which contains class name/file name/ class index? is there an easy way to make it?

as this :
`as this:

ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01.avi 1
ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c02.avi 1
ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c03.avi 1
ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c04.avi 1
ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c05.avi 1
ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c06.avi 1
ApplyEyeMakeup/v_ApplyEyeMakeup_g02_c01.avi 1
ApplyEyeMakeup/v_ApplyEyeMakeup_g02_c02.avi 1
ApplyEyeMakeup/v_ApplyEyeMakeup_g02_c03.avi 1
ApplyEyeMakeup/v_ApplyEyeMakeup_g02_c04.avi 1
ApplyEyeMakeup/v_ApplyEyeMakeup_g03_c01.avi 1
ApplyEyeMakeup/v_ApplyEyeMakeup_g03_c02.avi 1
ApplyEyeMakeup/v_ApplyEyeMakeup_g03_c03.avi 1
ApplyEyeMakeup/v_ApplyEyeMakeup_g03_c04.avi 1
ApplyEyeMakeup/v_ApplyEyeMakeup_g03_c05.avi 1`

thank you in advance,

**Comment by harvitronix** [comment]
The different versions just provide different ways to group your train/test videos. Ideally you'd want to test your model against each of the three splits to ensure it performs as expected. We only use the first one in our case.

If you have your own dataset, you just need to decide how you want to split them between train and test and then generate the paths. There's no real trick to it.
