### ISSUE TITLE
 ValueError: No model found in config file.

### ISSUE THREAD

**Issue by VictorLeeLk** [harvitronix/five-video-classification-methods#14]
When i run the file extract_features.py,I use the downloaded file inception_v3_weights_th_dim_ordering_th_kernels.h5 in my computer ,but it comes out one error at 
  File "C:\Anaconda2\lib\site-packages\keras\models.py", line 238, in load_model
    model_config = f.attrs.get('model_config')
I have changed the backend to theano.I try to solve the problem, some guys says it may that the program don't define the  architecture of  "Inception V3".but i am not sure.please help. thank you!

**Comment by harvitronix** [comment]
I haven't tried running this with the Theano background I'm afraid. I've only used TensorFlow. Can you try with TF and re-open if there's still an issue?
