### ISSUE TITLE
Can't find sequence train.py

### ISSUE THREAD

**Issue by DEGxm** [harvitronix/five-video-classification-methods#18]
Hi, when i run the file train.py i get the following message:

Can't find sequence. Did you generate them?
Traceback (most recent call last):
  File "train.py", line 114, in <module>
    main()
  File "train.py", line 111, in main
    load_to_memory=load_to_memory)
  File "train.py", line 53, in train
    X, y = data.get_all_sequences_in_memory(batch_size, 'train', data_type, concat)
  File "/home/dario/five-video-classification-methods/data.py", line 117, in get_all_sequences_in_memory
    raise

i am at a loss in this one, i already ran the previous code specified on the README, i ran the extract features.py for 2 classes only, dont know if it has anything to do with it

any guidance is appreciated

**Comment by harvitronix** [comment]
Hi @DEGxm, to generate the sequences, you need to run `extract_features.py`. This will create text files with the data needed by the other models.

Before running this script, be sure to decide on a sequence length and if you want to extract features for all classes (you set these at the top of the `extract_features.py` file). It can take 8+ hours to extract for all classes so I recommend you start with 10 or fewer.
