### ISSUE TITLE
train_cnn.py

### ISSUE THREAD

**Issue by sujiongming** [harvitronix/five-video-classification-methods#19]
def main(weights_file):
....
 **model = get_top_layer_model(model)**
 model = train_model(model, 10, generators)

I think get_top_layer_model(model) should be get_top_layer_model(base_model) . 
In your code,  none of  layers will be trained because all layers of model have been set " trainable = False"

**Comment by harvitronix** [comment]
My goodness you're right! Thank you, @sujiongming. PR coming.
