### ISSUE TITLE
move_files cant find files 

### ISSUE THREAD

**Issue by farshidrayhan** [harvitronix/five-video-classification-methods#21]
I have downloaded the dataset in the data folder and made 4 directories as instructed . Now when i run the move_files.py it cant find any files . I didnt change the code a bit . after extraction the files are in following format. data->UCF-101->ApplyMakeup->videos

![screenshot from 2017-09-03 16-45-14](https://user-images.githubusercontent.com/17830643/30002283-66806356-90c7-11e7-9900-a2b3d0accf51.png)

**Comment by cagbal** [comment]
The thing is, I think, you extracted rar manually. I also did it before and created PR #20  However, realized that if you use the command given in the tutorial, there should not be any problem.

**Comment by farshidrayhan** [comment]
Thanks for the solution . I wrote a bash script to solve that any way. Btw
Which command of the tutorial are you referring to ?


<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=farshidrayhan57@gmail.com&idSignature=22>

**Comment by cagbal** [comment]
unrar e UCF101.rar

**Comment by farshidrayhan** [comment]
ow... damn..  such simple things makes such a difference.



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=farshidrayhan57@gmail.com&idSignature=22>
