### ISSUE TITLE
Can we use multiple GPUs with this code ? 

### ISSUE THREAD

**Issue by shamanez** [harvitronix/five-video-classification-methods#28]
I have two 1080ti GTX GPUs. I am interested in the model 3(lrcn). So is there a way we can do distributed training with the Keras wrapper . Training two batches in 2 GPUs and update the weights as we do in normal TF.  I am very new to Keras. This will be really nice . Also I found this documentation in Keras about multi GPUs but it doesn't give much . 

[Multi GPU keras](https://blog.keras.io/keras-as-a-simplified-interface-to-tensorflow-tutorial.html#multi-gpu-and-distributed-training)

**Comment by harvitronix** [comment]
I haven't done this myself. This thread looks like a fun read, though: https://github.com/fchollet/keras/issues/2436 :)

Closing this issue for now. If you figure out how to apply it, would be awesome if you could share your implementation!
