### ISSUE TITLE
How to write the converted image sequence data in to a csv in Sequence folder . 

### ISSUE THREAD

**Issue by shamanez** [harvitronix/five-video-classification-methods#29]
I am refering to  [this line](https://github.com/harvitronix/five-video-classification-methods/blob/master/train.py#L99) .
Here the data type is **image**.  Which means I have to run **extract_features.py** . When running this what is happening is it ,

1. Just writing the image sequence data in to (pixel values of each frame) text file 
2. Run the image through inception V3 and get the last layer before softmax as features .

**Comment by harvitronix** [comment]
Hi @shamanez. When `data_type` is image, it's not using extracted features, it's using the image directly. The LRCN does both the CNN and RNN in the same model, so the weights are back propagated through the whole network, so there's no need to first extract features.

Does that answer your question?

**Comment by shamanez** [comment]
Yeah perfect.
