### ISSUE TITLE
Checkpointing in LSTM RNN model not working

### ISSUE THREAD

**Issue by Arjav96** [harvitronix/five-video-classification-methods#34]
I am finding some trouble in saving the LSTM RNN model through checkpointing. The model is not saving in the checkpoints folder. Please check it out!

**Comment by Mostafaghelich** [comment]
Yes, that's right. I have the same problem. How can I fix it?

**Comment by Arjav96** [comment]
I have figure it out. You just need to add checkpointer as one of the callbacks while doing model.fit().

**Comment by Mostafaghelich** [comment]
Thank you. It worked for me too.

**Comment by Mostafaghelich** [comment]
Thank you. It worked for me too.
