### ISSUE TITLE
UCF101 site does not work

### ISSUE THREAD

**Issue by Kcrong** [harvitronix/five-video-classification-methods#36]
Probably the same issue as #9
![image](https://user-images.githubusercontent.com/13450715/32786166-87bc770a-c996-11e7-864d-0d7efffbed7b.png)

Are there any other sites that have backed up your data?

**Comment by harvitronix** [comment]
Looks like there's another link here: https://storage.googleapis.com/thumos14_files/UCF101_videos.zip

This is from http://www.thumos.info/download.html

**Comment by harvitronix** [comment]
It's working again. Closing this.

**Comment by Kcrong** [comment]
👍
