### ISSUE TITLE
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

### ISSUE THREAD

**Issue by umlen-B** [harvitronix/five-video-classification-methods#4]
![prob](https://cloud.githubusercontent.com/assets/13407561/24653958/8942bce8-1955-11e7-8227-0b451294a132.png)

When I run extract_features.py this error comes up.

**Comment by harvitronix** [comment]
Hi @umlen-B, what version of Keras and TensorFlow are you using?

I pushed an update yesterday with a requirements.txt. Probably best to run `pip install -r requirements.txt` to make sure we're on the same version.
