### ISSUE TITLE
I want to know the result of each of your methods

### ISSUE THREAD

**Issue by PHJ007** [harvitronix/five-video-classification-methods#51]
Can you provide the results of each method?
Thanks!

**Comment by harvitronix** [comment]
@PHJ007 a slightly outdated list of results is available in the original bog post here: https://medium.com/@harvitronix/five-video-classification-methods-implemented-in-keras-and-tensorflow-99cad29cc0b5

Updated results are coming with a new release hopefully sometime soon...
