### ISSUE TITLE
Error in extractor.py; while running extract_features.py

### ISSUE THREAD

**Issue by TheGalileo** [harvitronix/five-video-classification-methods#52]
Hey!

I encountered the following error while running `extract_features.py`. Can you please help me out?

```
Traceback (most recent call last):
  File "extract_features.py", line 28, in <module>
    model = Extractor()
  File "/home/gaurav/Desktop/xModal/VideoClassification/extractor.py", line 18, in __init__
    include_top=True
  ...
  TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
```
The relevant section in `extractor.py` is:
```
14        if weights is None:
15            # Get model with pretrained weights.
16            base_model = InceptionV3(
17                weights='imagenet',
18                include_top=True
              )
```

Thanks in advance! :)

**Comment by TheGalileo** [comment]
Sorry, forgot to activate my tensorflow environment!

**Comment by ord1991** [comment]
Can you please explain how did you solve this issue?
thank you

**Comment by TheGalileo** [comment]
I think I already did; I had forgot to activate tensorflow environment. In most of the cases, you can do that using the following command:
`source ~/tensorflow/bin/activate` (assuming your tensorflow directory is in `~/`. 
Feel free to get in touch over email, if there is something that you'd like to discuss :)
