### ISSUE TITLE
Error in next() while running in python 2.7

### ISSUE THREAD

**Issue by shivarama23** [harvitronix/five-video-classification-methods#55]
Hi i am getting an error "TypeError: instance has no next() method" when running the "train.cnn" code for all the models.

**Comment by harvitronix** [comment]
@shivarama23 Can you paste the full error?

**Comment by shivarama23** [comment]
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 579, in data_generator_task
    generator_output = next(self._generator)
TypeError: instance has no next() method
___________________________________________________________________________________________________________
This is how the complete error looks.
Thanks

**Comment by TheGalileo** [comment]
May I suggest you to have a look at Issue #53?

**Comment by harvitronix** [comment]
Closing this as @BrownOfSummer has posted the fix in #53. If someone wants to submit a PR making the code more 2.7-friendly, I'd be happy to merge. Thanks.
