### ISSUE TITLE
"list index out of range" when running extract_features.py

### ISSUE THREAD

**Issue by ord1991** [harvitronix/five-video-classification-methods#56]
Hello all
when trying to run `extract_features.py` I get the following error:

`C:\Users\HTL99\Desktop\DL>extract_features.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\HTL99\Desktop\DL\extract_features.py", line 25, in <module>
    data = DataSet(seq_length=seq_length, class_limit=class_limit)
  File "C:\Users\HTL99\Desktop\DL\data.py", line 50, in __init__
    self.classes = self.get_classes()
  File "C:\Users\HTL99\Desktop\DL\data.py", line 82, in get_classes
    if item[1] not in classes:
IndexError: list index out of range`

Im currently on windows, so i needed to fix `foldernames` to `foldernames/` etc, but still did not manage to run it.
Any ideas?
Thanks.

**Comment by moonikwe** [comment]
Hi. I'd like to ask how you solved the problem? I'm experiencing the same thing.

**Comment by mohanrajmit** [comment]
Am also getting similar kind error while running code on windows machine.
Can you please help me to solve the above errors.


Regards
Mohan

**Comment by mohanrajmit** [comment]
Hi,

I am also getting similar kind of errors.

Can you please help me how you have solved the above error while running the code in windows machine.

Regards
Mohan

**Comment by bibinarose** [comment]
Does your data_file.csv has empty rows? If yes, delete it and try..

**Comment by luposmichaeljay** [comment]
How did you fixed this? Currently dealing with this error..
