### ISSUE TITLE
Variable-length sequence

### ISSUE THREAD

**Issue by reynierhdez** [harvitronix/five-video-classification-methods#58]
Hi Matt,

Thanks for your great work :)
How could the program be adapted to work with all the frames generated for different size videos?

Thanks!

**Comment by harvitronix** [comment]
You'll want to pick a sequence length equal to the size of the longest video, and then after creating your sequences, pad them before feeding into the model for training.

Take a look at Kera's `pad_sequences` method: https://keras.io/preprocessing/sequence/
