### ISSUE TITLE
About sequences

### ISSUE THREAD

**Issue by LZKSKY** [harvitronix/five-video-classification-methods#60]
After I ran train_cnn.py, I ran train.py as you say. But there're some errors. 
**ValueError: Can't find sequence. Did you generate them?**
And I checked the sequences file, and it's empty,  but it should saved features, isn't it?
I want to ask whether there're some code lost in train_cnn.py to save or some errors in train.py?
And how should I do to edit it?

**Comment by harvitronix** [comment]
Hi @LZKSKY. You need to run `extract_features.py` to generate the features. It's separate from `train_cnn.py`.
