### ISSUE TITLE
set rm.model.fit_generator(shuffle=false)

### ISSUE THREAD

**Issue by giovanniMen** [harvitronix/five-video-classification-methods#61]
First of all thanks for your great work!

When you use lstm in method 4 and you load batch with the fit_generator, if shuffle is True as default setting (see [https://keras.io/models/sequential/](url)) the batch will be mixed.
Is it correct?

I have this problem in my code, also can't set to false because it raise a `TypeError: fit_generator() got an unexpected keyword argument 'shuffle'`

I hope to understand this couse it's a bit confusing to me.

**Comment by harvitronix** [comment]
It shuffles the samples, but not the order of the sequence itself. Does that clear things up for you?
