### ISSUE TITLE
Gets stuck at epoch!

### ISSUE THREAD

**Issue by AdarshMJ** [harvitronix/five-video-classification-methods#66]
Gets stuck at epoch 1/(no. of epochs specified). Doesn't proceed further

![screen shot 2018-01-18 at 11 24 10 pm](https://user-images.githubusercontent.com/24205200/35113230-b9937e02-fca6-11e7-9188-6691fc2e2903.png)
![screen shot 2018-01-18 at 11 23 57 pm](https://user-images.githubusercontent.com/24205200/35113232-b9db37b0-fca6-11e7-8112-80edd1262442.png)

**Comment by harvitronix** [comment]
Best guess is it's running out of memory... try with a much smaller network (change the LSTM to 64 and dense to 32) and see if it runs then.
