### ISSUE TITLE
get stuck at adding lstm layer

### ISSUE THREAD

**Issue by VictorLeeLk** [harvitronix/five-video-classification-methods#77]
after extracting features by running extract_features.py，then  I run train.py,the model is lstm,but when print the input shpe (16,2048),it got stuck at model.add(LSTM(...))，what's wrong?thank you!

**Comment by harvitronix** [comment]
When you say it got stuck, do you mean it froze? If that's the case, it's likely that you've run out of memory. The LSTM defaults to 2048 units which is quite memory intensive. Reduce it significantly (try just 8 units) to see if that solves the problem, then scale up to the point that it stops working, and use the one before that.
