### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by Anuj009** [harvitronix/five-video-classification-methods#8]
In extractor.py at line 53 I get IndexError for features[0][0][0] for imagenet weights. I only see 2 dimensions when I try to print the features.
Also, can you give us a brief but precise stepwise guide as to in which order the files need to be executed? It gets a bit confusing after the 3 file in data.

**Comment by harvitronix** [comment]
@Anuj009 The issue in `extractor.py` should be fixed now. Thanks for bringing it up (months ago!).
