### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.python'

### ISSUE THREAD

**Issue by Joeng22** [harvitronix/five-video-classification-methods#81]
>> import keras

following errors get printed
>>from tensorflow.python.training import moving_averages
ModuleNotFoundError: No module named 'tensorflow.python'

any idea??

**Comment by sayanmutd** [comment]
Please change the backend of Keras to Theano by installing theano and editing the ~/.keras/keras.json  file

**Comment by harvitronix** [comment]
I believe this is just because you don't have TensorFlow installed... see here for installation instructions: https://www.tensorflow.org/install/

**Comment by josecyc** [comment]
I had to unintstall tensorflow from the python site packages manually and reinstalled it and the issue went away. This might be caused by having tensorflow in conda and python site packages, whenever you uninstall and install from conda but not from python site packages the issue appears.
